name: Deploy Prod

on:
  push:
    tags:
      - 'v**'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Download `.serverless` state from S3
      run: aws s3 sync s3://serverless-next-aws/.serverless .serverless --delete 

    - name: Deploy to AWS
      run: npx serverless

    - name: Upload `.serverless` state to S3
      run: aws s3 sync .serverless s3://serverless-next-aws/.serverless --delete 